### ISSUE TITLE
No traces for mysql 8+

### ISSUE THREAD

**Issue by gokhanoner** [DataDog/dd-trace-java#2339]
I have a Play App that uses MySQL 8 & using latest javaagent, I cannot see MySQL traces or any connection to MySQL DB at all. I changed the agent to 0.71.0 & everything is working. 
I saw that `"com.mysql.cj.jdbc.JdbcConnection"` marked as concrete type but it's actually an interface. Could that be the reason?

**Comment by richardstartin** [comment]
Hi @gokhanoner thanks for reporting this issue. We changed the way the JDBC instrumentation worked in 0.72.0, so that rather than match all implementations of `java.sql.Connection` and detect and filter out wrappers and proxies at connection time, we just match the native connections we know about. This significantly reduces the overhead of our JDBC instrumentation on user applications. A mistake was made with MySQL, which should be fixed by #2338, and will be followed by more integration testing for major databases.

**Comment by gokhanoner** [comment]
@richardstartin glad that it’s fixed quickly. Quick question: I saw that you added the impl class instead. Based on https://github.com/mysql/mysql-connector-j/blob/release/8.0/src/main/user-impl/java/com/mysql/cj/jdbc/NonRegisteringDriver.java#L183, there are multiple impl of the connection class. I believe you’re only supporting the default connection impl?

**Comment by richardstartin** [comment]
@gokhanoner the other connection types delegate to `ConnectionImpl` - it's these proxies and wrappers we avoid filtering out at runtime.

https://github.com/mysql/mysql-connector-j/blob/18bbd5e68195d0da083cbd5bd0d05d76320df7cd/src/main/user-impl/java/com/mysql/cj/jdbc/ha/LoadBalancedConnectionProxy.java#L87
https://github.com/mysql/mysql-connector-j/blob/18bbd5e68195d0da083cbd5bd0d05d76320df7cd/src/main/user-impl/java/com/mysql/cj/jdbc/ha/MultiHostConnectionProxy.java#L358

**Comment by NicklasWallgren** [comment]
We have encountered this "issue" as well and was forced to revert to an older version of the dd-java-agent.

Do we need to make any configuration changes inorder for 0.72.0+ to work seamlessly with spring-data and hibernate?

The datadog support wasn't aware of these changes either, so they couldn't pinpoint the issue.
