### ISSUE TITLE
Rabbitmq spring auto instrumentation is missing child relationship in subsequent spans

### ISSUE THREAD

**Issue by kevtainer** [DataDog/dd-trace-java#2691]
With the new spring boot auto-instrumentation for RabbitMQ, the primary operation `amqp.command` does not maintain the child relationships with spans that are invoked downstream. This is contrary to almost every other primary operation I can find.

example:

* scheduled.call (the parent trace doesnt end until all the downstream calls are finished)
![image](https://user-images.githubusercontent.com/3759919/117191528-4b092900-ada6-11eb-8c98-fecf148479e8.png)

* http.request / servlet.request (same here)
![image](https://user-images.githubusercontent.com/3759919/117191791-96bbd280-ada6-11eb-9a33-facfc7772481.png)

* amqp.command `basic.deliver` ends up reporting as 94.4us
![image](https://user-images.githubusercontent.com/3759919/117192008-da164100-ada6-11eb-9671-34d86b51cc7c.png)
* disregarding that the downstream calls are still in the same service/trace:
![image](https://user-images.githubusercontent.com/3759919/117192698-a687e680-ada7-11eb-981f-737935197be3.png)

**Comment by richardstartin** [comment]
@kevtainer what is the parent of the downstream aws-sdk calls according to the trace? The rabbitmq span, or something else? 
* If it's the former, is the concern just about the reported latency of the rabbitmq span? If it's the former, this may be correct from a physical view of the world - this can happen with asynchronous workflows, but we can look in to creating better synthetic spans for logical transactions.
* If it's the latter, then there is likely a nonstandard thread pool which we will need to track down and instrument.

**Comment by richardstartin** [comment]
@kevtainer thanks, this is all useful information - it's likely there is a custom thread pool downstream from the listener. Do you mind emailing a link to this issue to support@datadoghq.com so we can take a closer look?

**Comment by kevtainer** [comment]
@richardstartin thanks, i've opened a support case and am working with a SE to provide some more information. ref#484400

**Comment by richardstartin** [comment]
Hi @kevtainer thanks for doing that, I have looked at the traces now. There are three issues here which I will outline here for the sake of visibility:

1. **Is there a parent-child relationship between the `amqp.command` `basic.deliver` span and the `rabbit.listener` span?** Yes, there is, but that doesn't mean that the time in the `amqp.command` span should outlive the listener, because the listener execution is asynchronous. The other examples given above are generally synchronous, e.g. servlet requests, okhttp calls, scheduled tasks. From a physical point of view, this is correct, but it sounds like you would like to be able to visualise a logical transaction spanning the message delivery, its dispatch to the listener pool, and the listener's invocation. This is something we could look in to implementing (in addition to the existing spans) if it is useful.
2. **The service page for `rabbit.listener` is blank, but for `amqp.command` it is not.** This is because `rabbit.listener` is neither [top level](https://docs.datadoghq.com/tracing/visualization/#top-level-span) (its service name differs from its parent's) nor _measured_. Given the asynchronous nature of this message flow, this is unfortunate, because it means you have latency metrics for the practically instantaneous message delivery and dispatch, but not for the listener which is doing the work. We can fix this easily by making `rabbit.listener` measured. Or, if we were to create a logical span spanning the entire message flow as mentioned above, we would make that span measured so you get latency metrics for it.
3. **The `amqp.command` operation encompasses too many different operations, such as `basic.ack`, which skews latency metrics.** Yes, this seems unfortunate. However, you can ignore resources in your [agent configuration](https://docs.datadoghq.com/tracing/setup_overview/configure_data_security/?tab=mongodb#exclude-resources-from-being-collected) by adding "basic.ack" to the list, which means the `amqp.command` latency metrics will make more sense at an operation level. This is something we will review so it works better out of the box.

**Comment by mcculls** [comment]
We added a measured `amqp.consume` span in 0.82.0 to address point 2 - in the 0.88.0 release we're improving the resource name for that span to capture the queue the message was consumed from.

The 0.88.0 release will also include a new feature to improve the RabbitMQ span structure and service maps - by setting `-Ddd.rabbit.legacy.tracing.enabled=false` (ie. turning _off_ the old span structure) you'll now get a "time-in-queue" span representing how long the message was on the queue from the time it was produced to the time it was consumed.

**Comment by mcculls** [comment]
If you're interested in trying out this new feature before the 0.88.0 release then you can use this pre-release snapshot: https://oss.sonatype.org/service/local/repositories/snapshots/content/com/datadoghq/dd-java-agent/0.88.0-SNAPSHOT/dd-java-agent-0.88.0-20210923.123746-18.jar
