### ISSUE TITLE
Clarify which JVM supported with profiling

### ISSUE THREAD

**Issue by monwolf** [DataDog/dd-trace-java#3005]
In the documentation you say Openjdk-11 is supported to profile an application. In my opinion you should say: Openjdk11-Hotspot is supported, because openjdk11-openj9 is not supported. 

I would like you add this clarification to the error message:

```
WARN com.datadog.profiling.agent.ProfilingAgent - Not enabling profiling; it requires OpenJDK 11+, Oracle Java 11+, or Zulu Java 8 (1.8.0_212+).
```

and your docs:

```
The Datadog Profiler requires JDK Flight Recorder. The Datadog Profiler library is supported in OpenJDK 11+, Oracle Java 11+, OpenJDK 8 (version 8u262+) and Zulu Java 8+ (minor version 1.8.0_212+). All JVM-based languages, such as Scala, Groovy, Kotlin, and Clojure are supported. To begin profiling applications:
```

**Comment by flodav** [comment]
Hi Monwolf and thanks for your report!

The IBM JVM is called OpenJ9 and does not contain the OpenJDK word anywhere. OpenJ9 has been entirely implemented by IBM and does not contain code that comes from the hotspot JVM.

See https://github.com/eclipse-openj9/openj9#what-is-eclipse-openj9 : _Eclipse OpenJ9 is an independent implementation of a Java Virtual Machine. "Independent implementation" means it was built using the Java Virtual Machine specification without using any code from any other Java Virtual Machine._

To be more precise, OpenJDK is an open source implementation of Java, and Hotspot is the JVM implementation that belong to this project. Hence OpenJDK and OpenJ9 are 2 different projects. 

Hence the wording for the error message and the documentation seems correct to me, let me know if you have more arguments if you think otherwise.

Thanks,
Florian

**Comment by monwolf** [comment]
Hey! 

Thanks for the resposne, I think my confusion were feeded by "the about" of the project:

```
Eclipse OpenJ9: A Java Virtual Machine for OpenJDK that's optimized for small footprint,
```

And the webpage adoptjdk:

https://adoptopenjdk.net/

![image](https://user-images.githubusercontent.com/1116133/129573099-82870372-460f-4b14-9470-9626e90e7355.png)

For them both JDK are OpenJdk. 
For the binaries too:
Hotspot:
![image](https://user-images.githubusercontent.com/1116133/129573646-4f26c8e2-d80b-4a52-8d2c-9223f6b0d3a2.png)
Openj9:
![image](https://user-images.githubusercontent.com/1116133/129573782-3a4687bd-40af-498a-a72c-c6e92de9e9a0.png)

**Comment by philippneugebauer** [comment]
I need to agree with @monwolf's point of view. Till I saw this issue, I was sure openj9 is supported regarding the information on the adoptopenjdk page

**Comment by bm1549** [comment]
Thank you for the feedback. This was included in https://github.com/DataDog/dd-trace-java/pull/3393
