### ISSUE TITLE
Regression in ExecutorInstrumentation v0.7.0?

### ISSUE THREAD

**Issue by mwirges** [DataDog/dd-trace-java#304]
What: dd-java-agent v0.7.0

Attempting to run some tests moving from v0.6.0 to v0.7.0 agent, I noticed I was no longer getting trace continuation through an executor service.

Looking at the diff here: https://github.com/DataDog/dd-trace-java/compare/v0.6.0...v0.7.0

It seems that for ExecutorInstrumentation.java the Wrap*Advice methods (intercepting ExecutorService.submit) was changed to only continue the current scope span IF the setAsyncPropagation flag is set on the TraceScope already.   But this is confusing because how would this ever get set other than explicitly asking it to be?

Say I have some jax-rs resource that submits some work to an executor which further creates new spans, say with an apache-httpclient request to somewhere:

```
@Path('/foo')
class Foo {
   ExecutorService someExecutor = ExecutorService.newFixedThreadPool(2);
    @GET
    String foo() {
       return someExecutor.submit(() -> { someContrivedAsyncHttpCallThatReturnsAString(); }).get();
    }
}
```
In this case a brand new trace is opened when the callable is executed by the executor and the instrumented apache-httpclient is invoked -- and it is _not_ linked to the trace started for the jax-rs method.

However, if I fool it by explicitly setting the asyncPropagation flag it will work:

```
@Path('/foo')
class Foo {
   ExecutorService someExecutor = ExecutorService.newFixedThreadPool(2);
    @GET
    String foo() {
       ((TraceScope)GlobalTracer.get().scopeManager().active()).setAsyncPropagation(true);
       return someExecutor.submit(() -> { someContrivedAsyncHttpCallThatReturnsAString(); }).get();
    }
}
```

I.e. I see the resulting continuation log lines:

```
...
[XNIO-1 task-3] DEBUG datadog.trace.agent.ot.PendingTrace - traceId: 4832245528826328661 -- registered continuation datadog.trace.agent.ot.scopemanager.ContinuableScope$Continuation@d0cf6b2. count = 2
[XNIO-1 task-3] DEBUG datadog.trace.instrumentation.java.concurrent.ExecutorInstrumentation$DatadogWrapper - created continuation datadog.trace.agent.ot.scopemanager.ContinuableScope$Continuation@d0cf6b2 from scope datadog.trace.agent.ot.scopemanager.ContinuableScope@497bfe34
...
```

Is it intentional that this flag be set? 

If yes, then bummer. It just breaks existing functionality and leaves a bunch of disconnected traces and makes it very clumsy in the code using the agent, because now some work has to be done to explicitly set the async propagation flag and _requires_ I bring in the dd-trace-ot dependency... unless I'm missing something?

**Comment by realark** [comment]
Hi @mwirges, yes it is intentional that the flag be set. However we can explore some options to make things more smooth on your end.

First, some context. Propagating our trace by default can cause problems because the executor instrumentation is too low level to know where to start and stop automatically. This sometimes causes traces to be linked across logical boundaries. We've seen http servers with code like this:

```
writeResponseToUser(response);
// the executor instrumentation will link this call to submit
// causing the two requests to be captured under the same trace
threadPool.submit(processNextRequestCallback);
```

To avoid this issue we're using higher level instrumentation to turn the async instrumentation on and off at the appropriate times.

For example, in play we enable async instrumentation when the [request comes in](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play/PlayInstrumentation.java#L102) and disable when the [response goes out](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play/PlayInstrumentation.java#L205).


Setting this flag does not require a dependency on `dd-trace-ot`, just on `dd-trace-api`, which is a smaller library with no transitive dependencies. https://mvnrepository.com/artifact/com.datadoghq/dd-trace-api/0.7.0

As a solution, we can add async logic to our builtin servlet instrumentation similar to what we do with play. That will give you the old behavior when using async libraries inside a servlet request. What do you think about that?

**Comment by mwirges** [comment]
@realark yeah understood on not wanting to inadvertently continue unrelated things.   I do think turning it on from servlet instrumentation automatically would be helpful.   Thanks for clarifying on dd-trace-api; I'll give that a whirl in the meantime.
