### ISSUE TITLE
Add support for Vert.x 4.x

### ISSUE THREAD

**Issue by sirinn** [DataDog/dd-trace-java#3143]
Hi,

according to your docs https://docs.datadoghq.com/tracing/setup_overview/compatibility_requirements/java/. There is no support for Vert.x 4.x upgrade. It has implemented many new tracing functionality. It would be appreciated if you can continue with the support for next major release.

Thanks

**Comment by bergbrains** [comment]
We are also in need of Vertx 4.x support.

**Comment by chris-brace** [comment]
> could you tell us what vertx modules you are using? IE: for vertx 3 we support web, rx, redis, and mysql.

super important for us as well. we're using web, redis, postgres here.

**Comment by devinsba** [comment]
I don't know when we will end up being able to upgrade to vert.x 4, to get something working you can use the Opentracing support that Vertx provides: https://vertx.io/docs/vertx-opentracing/java/

Then if you add `implementation group: 'io.opentracing', name: 'opentracing-util', version: '0.33.0'` you can add the datadog tracer as the tracer: with a modified version of the second example, with the datadog javaagent GlobalTracer will return an OpenTracing tracer

```
Tracer tracer = GlobalTracer.get();
Vertx vertx = Vertx.vertx(new VertxOptions()
  .setTracingOptions(
    new OpenTracingOptions(tracer)
  )
);
```

**Comment by sirinn** [comment]
Hey @devinsba, 

thanks for reaching back, we tried this workaround even before writing here and our major problem with it is that the DD agent is still trying to execute all the broken instrumentation even on unsupported version of vert.x 4 and is creating _a lot_ of noise and duplication of traces. Where it's really 50/50 chance of you finding the broken trace from instrumentation or correct one from custom tracing using vert.x open tracing extension on web. It really became unusable for us right now, which is very unfortunate vert.x 4 major version was released some time ago. 

Is there something we can do to help you give this integration a priority ? Official upgrade request from big tech customer ?

Would there be a possibility to disable the instrumentation and only allow custom tracing ? Deploying a dedicated OpenTracing collector is not an option for us as we are also using the DD agent for CPU profiling. 

And one more question, could you please confirm that you would have time to review/approve/release a public contribution for vert.x 4 support if it was contributed by someone ?

**Comment by gsaqui** [comment]
@sirinn did you ever receive an answer from @devinsba  via a different communication channel?  Just wondering if there has been any movement around this issue as it's impacting us as well.

**Comment by sirinn** [comment]
Hey @gsaqui,

No, I haven't received any further answers or communications from @devinsba or anyone else from this project. We are also not really satisfied with the insufficient movement on this front and started considering switch to different tracing solutions, if no workaround or solution is found soon.

**Comment by devinsba** [comment]
Sorry folks for the delay, to answer a couple questions:

Yes you can disable automatic instrumentation using system properties, `dd.trace.integration.<name>.enabled=false`. So for vert.x I would expect probably wanting to disable `netty`, and `vertx`. There are potentially others but if you have tracer debug logging enabled (`dd.trace.debug=true`) you can see what gets activated and disable them if needed. (also note properties can be converted to environment variables by converting to uppercase and swapping all `.` and `-` with underscores)

Second, we definitely do accept community contributions. Review of something like this would be a little easier than something completely brand now since we can compare to the old version. See https://github.com/DataDog/dd-trace-java/pull/3210 and https://github.com/DataDog/dd-trace-java/pull/3211 for recent examples

Finally, the fact that it is partially activating for Vertx 4 would seem to be a bug, would you be able to reach out to support@datadoghq.com to share debug logs so we can figure that out, even with support for vertx 4 specifically added we would need to fix whatever you are seeing

**Comment by gsaqui** [comment]
Hi @devinsba - is there any plan for Vertx 4.0 to be supported?

**Comment by LuboViluda** [comment]
Hello @devinsba,

- I have opened Vertx 4 issue with DD support for our account.
- I could confirm that we were able to disable intergration by env vars as you described, ofc then everything needs to be instrumented manually.
- I have opened MR with changes to migrate instrumentation to Vert.x 4. I'm not sure about test suite changes needed (I tried to migrate from Vert.x 3 web suite) - more info in MR - https://github.com/DataDog/dd-trace-java/pull/3557. Could you take a look and provide some guidance on how to proceed? [MR](https://github.com/DataDog/dd-trace-java/pull/3557)
- kudos to @sirinn for describing some of the migration steps

Regards,
Lubo

**Comment by akleiman** [comment]
With the MR above merged, is this issue resolved?

**Comment by akshaypatidar1999** [comment]
@devinsba Is there any plan to integrate redis, and MySQL modules for vertx4?
We are currently upgrading our services to vertx 4 but are not able to get spans for redis/mysql IO calls

**Comment by devinsba** [comment]
Please reach out to support@datadoghq.com with that feature request
