### ISSUE TITLE
Performance degradation with tracing enabled

### ISSUE THREAD

**Issue by alok1111** [DataDog/dd-trace-java#3499]
Our Java 11 project is based on Play Framework. For database requests we use jOOQ ORM.
Running instance faces performance degradation when I enable tracing:
- Startup time increases from 1 minute to 3 minutes.
- First database request after the startup takes 30 seconds even though it isn't heavy. It looks like jOOQ initialization takes too long.
- Database queries that request big amounts of data (1 million rows) take two times longer to complete.

Core dependencies versions:
- com.typesafe.play/play - 2.8.15
- org.jooq/jooq - 3.16.5
- com.colisweb/sbt-datadog - 2.1.0  + dd-trace - 0.99.0

Please advice how to troubleshoot this.

**Comment by mcculls** [comment]
Hi @alok1111 there will always be some overhead as the JVM warms up and classes are loaded because the tracer needs to intercept class-load requests, match classes against various filters, and if necessary transform the class to add advice, etc.

We are in the middle of an effort to reduce this overhead, I'll update this issue when there's something you can test.

Regarding the additional database query time, that is unexpected because once the JVM has warmed up, and all the necessary classes are loaded, then the overhead of actual tracing (compared to the upfront cost of transforming classes) should be minimal.

To troubleshoot it I'd suggest turning off the JDBC instrumentation to see if that makes a difference - if it does then we know that it's related to that specific instrumentation. To turn off the JDBC instrumentation add this system property:
```
-Ddd.integration.jdbc.enabled=false
```
This will mean you won't receive JDBC traces while this instrumentation is turned off. so this is not a workaround. You'll need to remove it to get back JDBC traces. But it would help us identify whether a specific instrumentation is involved.

If that doesn't help then the next step would be to temporarily turn on [debug logging](https://docs.datadoghq.com/tracing/troubleshooting/tracer_debug_logs/), run the application with example queries that show the problem, then collect the application logs and attach them to a support ticket (don't attach them here.)

Remember to turn off debug logging after collecting the logs, because it is very verbose.
