### ISSUE TITLE
Instrumentation of custom JDBC database driver

### ISSUE THREAD

**Issue by bbaga** [DataDog/dd-trace-java#3643]
Hello,
We have a custom database driver that hides some complexity (sharding, loadbalancing, etc) over our MSSQL servers and we've noticed that the instrumentation from the DD agent isn't the same as if we were using the standard `sqlserver` driver.

We've traced the issue back to our connection string, since we register our driver with `our-custom-driver`, the connection string starts with `jdbc:our-custom-driver:sqlserver://...` that the `datadog.trace.bootstrap.instrumentation.jdbc.JDBCConnectionUrlParser` (understandably) can not parse, which leaves us with much less data on our span's than we'd normally would have. Notably we are missing the `db.user` and `peer.hostname` tags on query spans.

Further more, our driver will manage multiple connections under the hood using the standard `sqlserver` driver which are invisible at this point (we've found [a release note](https://github.com/DataDog/dd-trace-java/releases/tag/v0.72.0) which might explain this).

Is there a recommended way of enabling instrumentation of custom drivers and the wrapped connections?

We are using [v0.101.0](https://github.com/DataDog/dd-trace-java/releases/tag/v0.101.0) at the moment.

**Comment by ymengesha** [comment]
To elaborate further on the above points:

Our custom driver delegates calls to `sqlserver` driver, hence the connections obtained from our custom driver are plain `sqlserver` connections. With this in mind, we have identified [the place](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DriverInstrumentation.java#L64) where we could potentially query the relevant info from the connection object. In this PR #4112 , we attempt to read off the query string and user name from the connection's metadata so that `datadog.trace.bootstrap.instrumentation.jdbc.JDBCConnectionUrlParser` could parse the `sqlserver` connection string without a problem. With our limited testing, we were able to verify that our tags on the query spans were back using this change.

Validating this change as a potential contribution wasn't easy though. The available test suites were flaky to properly check the effects of this change. Some tests were failing even without any code changes. 

Is this a viable approach to fix this gap? Any help would be appreciated!
