### ISSUE TITLE
Is there a way to capture input arguments with a span tag?

### ISSUE THREAD

**Issue by zzerjae** [DataDog/dd-trace-java#4638]
Hello, DataDog team.

Is there a way to capture input arguments with a span tag when the trace target methods specified in DD_TRACE_METHODS are executed?

**Comment by mcculls** [comment]
Hi @zzerjae - this is another place where you could use custom instrumentation to capture additional information: https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/java/

The DD_TRACE_METHODS instrumentation doesn't do this by default because Java bytecode (and the reflection API) doesn't provide argument names unless the class has been compiled with `-parameters`, which is not common - by default we only have the argument index. Also some arguments might be very large, or might not map well to tag format .

So this would be another feature request. We'd need to have a mechanism for users to declare which arguments to capture, and also tell us which index each argument name is expected to have (or limit the feature to use tags based on the argument index) - unfortunately any code refactoring could change the argument indexes, which could make this mapping fragile.

**Comment by zzerjae** [comment]
Thanks for your kind comment!
