### ISSUE TITLE
About latest-java-tracer question

### ISSUE THREAD

**Issue by Cazen** [DataDog/dd-trace-java#4836]
Good day :)
We use datadog-agent of latest version when start up our container.
It worked fine until yesterday, but when I run it through the following command, an error occurs
---
1. wget -q -O /dd-java-agent.jar https://dtdg.co/latest-java-tracer
2. java -javaagent:/dd-java-agent.jar -Ddd.profiling.enabled=true -Ddd.service=service-name -Ddd.env=$SPRING_PROFILES_ACTIVE -Ddd.version=1.0.0 -jar app.jar
result
Error opening zip file or JAR manifest missing : /dd-java-agent.jar
Error occurred during initialization of VM
agent library failed to init: instrument
---

In case of using latest-java-tracer, an error occurs, but when I use the old version (wget -q -O /dd-java-agent.jar https://dtdg.co/java-tracer-v1) and run the same command instead, it works fine.
I didn't find anything changed on the description page
(https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/java/?tab=containers). 
Could this be a bug? Or is it a usage error?

**Comment by Cazen** [comment]
It started working again. I don't know why because I didn't fix the code
I'll close this issue because I don't know how to delete it.

**Comment by bantonsson** [comment]
Hi @Cazen, I was just about to comment that the download worked on this side of the globe. Great that it started working again for you. The downloads in the end come from GitHub, and the problem was likely related to GitHub having some issues and degraded performance the last few days https://www.githubstatus.com/history
