### ISSUE TITLE
OpenTelemetry Tracing Experimental Feature Questions

### ISSUE THREAD

**Issue by tony-schellenberg** [DataDog/dd-trace-java#4935]
This could be as simple as user error but I tried using a number of features with OpenTelemetry and DataDog but it didn't seem to work for everything I tested. I set the experimental `DD_INTEGRATION_OPENTELEMETRY_EXPERIMENTAL_ENABLED` feature with DataDog java version `1.10.1`. Out of the box, I was able to get the global tracer and add manual spans without an issue and it's an awesome start.

However, I did run into several things that didn't work as I was anticipating:
- Using the OpenTelemetry `@WithSpan` and `@SpanAttribute` did not seem to create a new span for the annotated method or add the attribute
- Creating a new trace by creating a span with `.setNoParent()` did not create a new trace but it did create the span. Changing to `.setParent(null)` created a new trace
- Calling `.addLink` with the context of a span from another trace does not seem to link the traces together. I ended up with two independent traces from the service and I couldn't see any relationship generated between the two traces
- Calling `.setAttribute()` on the span does not seem to add the information in a way that appears in the DataDog UI

I am happy to provide more information on any of the above and appreciate any advice or suggestions you can offer.

**Comment by PerfectSlayer** [comment]
Hi Tony!

Thanks for your feedback, appreciated 🙏 
As you noted, the support of _Open Telemetry_ is still experimental and we plan to improve it through time.

> Using the OpenTelemetry @WithSpan and @SpanAttribute did not seem to create a new span for the annotated method or add the attribute

That is right. We only support `Tracer API` right now, and automatic instrumentation `Annotations` are not supported yet.
This is a topic that is currently under consideration as it already received few requested about it.

> Creating a new trace by creating a span with .setNoParent() did not create a new trace but it did create the span. Changing to .setParent(null) created a new trace.

Thanks, I will investigate this issue.

> Calling .addLink with the context of a span from another trace does not seem to link the traces together. I ended up with two independent traces from the service and I couldn't see any relationship generated between the two traces.

`Context` API support is very limited right now (mainly limited to current Span) and Span links are not supported for the moment. Feel free to share your use case with us when we will consider the feature.

> Calling .setAttribute() on the span does not seem to add the information in a way that appears in the DataDog UI

This is supposed to work. Again, I will try to reproduce. Feel free to share any attribute key/value pair you used that was not reported.

Best,
Bruce

**Comment by tony-schellenberg** [comment]
Super! Thanks for the detailed reply.

> Context API support is very limited right now (mainly limited to current Span) and Span links are not supported for the moment. Feel free to share your use case with us when we will consider the feature.

It's not a highly common use case but we have situations where something will trigger a number of jobs/threads to run some activity. It's convenient for us to have each of those worker actions traced separately so that we can look at latency and other properties using the standard service views in DataDog but it's also useful to see the overall trace that started everything with all of the internal traces that it spawned.

>    Calling .setAttribute() on the span does not seem to add the information in a way that appears in the DataDog UI
>
> This is supposed to work. Again, I will try to reproduce. Feel free to share any attribute key/value pair you used that was not reported.

I didn't try it in a broad sense so I went back and tried again in more detail and here's what I found:
- I was able to set arbitrary metadata onto the span without any trouble
- When I tried to set "error.type" and "error.message" on the span, the "error.message" entry is populated and there is an error in the "Errors" tab when I look at the trace. However, in the flame graph the UI treatment seems to be missing (it doesn't have the red `!` and surrounding box)
- When I tried to access the attributes on the root span of the trace, it didn't seem to work for arbitrary attributes or the error ones. I was accessing that with something like ```Span.fromContext(Content.root()).setAttribute(...)```.

That last point about setting errors on the root span is useful when you have a situation where you want the whole trace to be marked as an error so that it shows up as errors in places like the hit rate graph for the service.

Please let me know if there's anything you'd like me to try out or if I can provide any additional detail.

Cheers,
Tony

**Comment by PerfectSlayer** [comment]
> Creating a new trace by creating a span with .setNoParent() did not create a new trace but it did create the span. Changing to .setParent(null) created a new trace.

After investigation, you were right, there was an issue that I fix.
You will be able to create a new root span with `setNotParent()` and I will recommend not using `setParent(null)` once patched as giving a `null` context feels more like a workaround trick rather than a proper OTel API usage 😉  

> I was able to set arbitrary metadata onto the span without any trouble

At least, that's a good start!

> When I tried to set "error.type" and "error.message" on the span, the "error.message" entry is populated and there is an error in the "Errors" tab when I look at the trace. However, in the flame graph the UI treatment seems to be missing (it doesn't have the red ! and surrounding box)

Can you try to add the following tag: `("error", "true")`? It should set the error flag for the span and I hope the UI will properly handle it.

> When I tried to access the attributes on the root span of the trace, it didn't seem to work for arbitrary attributes or the error ones. I was accessing that with something like Span.fromContext(Content.root()).setAttribute(...).

I don't think `Span.fromContext(Context.root())` should return the root span.
When checking at [the API documentation](https://github.com/open-telemetry/opentelemetry-java/blob/38bf4d8ec0d794f9be77d2fe33b1ed99f5262eef/context/src/main/java/io/opentelemetry/context/Context.java#L95-L102) or the [root context implementation](https://github.com/open-telemetry/opentelemetry-java/blob/38bf4d8ec0d794f9be77d2fe33b1ed99f5262eef/context/src/main/java/io/opentelemetry/context/ArrayBasedContext.java#L30), you won't have anything stored in the (immutable) root context. So `Span.fromContext(Context.root())` [is returning an _invalid_ span](https://github.com/open-telemetry/opentelemetry-java/blob/38bf4d8ec0d794f9be77d2fe33b1ed99f5262eef/api/all/src/main/java/io/opentelemetry/api/trace/Span.java#L49-L50) so you won't have `NullPointerException` but all your calls to `setAttributes()` will be lost. 

> That last point about setting errors on the root span is useful when you have a situation where you want the whole trace to be marked as an error so that it shows up as errors in places like the hit rate graph for the service.

I agree that would be something useful that seems missing from Open Telemetry API.

Best,
Bruce

**Comment by tony-schellenberg** [comment]
Thanks for all of the help on this. I'll try out the new context key when it's available.

**Comment by kodstark** [comment]
It is great that tags are added to traces using OpenTelementry API. I am running it with Datadog JavaAgent having DD_INTEGRATION_OPENTELEMETRY_EXPERIMENTAL_ENABLED=true. However looks that metrics are not supported. I know that this repository is about tracing in DD Java Agent and where I can ask for OpenTelementry metrics support in Datadog JavaAgent?

```
// it is working
import io.opentelemetry.api.trace.Span;

        Span activeSpan = Span.current();
        if (activeSpan != null) {
            activeSpan.setAttribute("sometag", tagValue);
        }

// it is not working
import io.opentelemetry.api.OpenTelemetry;
import io.opentelemetry.api.metrics.LongCounter;
import io.opentelemetry.api.metrics.Meter;

    private LongCounter counter;

    @Autowired
    public void updateOpenTelemetry(OpenTelemetry openTelemetry) {
        Meter meter = openTelemetry.getMeter("abc");
        counter = meter.counterBuilder("abc.count")
                .setDescription("ABC").setUnit("1").build();
    }

    public void onMessage(Message inMsg) {
        counter.add(1);
        ...
    }
```

**Comment by tony-schellenberg** [comment]
@kodstark We've been doing it based on the information here: https://docs.datadoghq.com/opentelemetry/

Specifically, using Option 2 which pushes the OTEL metrics right to the agent rather than having an in memory collector: https://docs.datadoghq.com/opentelemetry/otlp_ingest_in_the_agent/?tab=host

From what I can recall, it was basically exactly what is listed in the second page I linked; we had to set an env var for the agent to enable the end point (we used gRPC) and then add the env var to the application. The rest of it was totally standard OpenTelemetry metrics code.

**Comment by kodstark** [comment]
@tony-schellenberg Thank you for reply. I am familiar with that documentation and I was able to visualize metrics in Datadog UI from OpenTelementry API using OTEL Java Agent sending data to Datadog Agent or to OTEL Collector. However I asked about using OpenTelementry API with Datadog Java Agent (not OTEL Java Agent) sending data to Datadog Agent - in that case flag DD_INTEGRATION_OPENTELEMETRY_EXPERIMENTAL_ENABLED=true enabled traces produced by OpenTelemetry API but not metrics (I found that flag by accident as it is not part of [official documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) yet).

I started research from using AWS OTEL Java Agent and AWS OTEL Collector exporting metrics and traces to Datadog. However neither Amazon nor Datadog are willing to provide commercial support for this setup citing they are Open Source libraries even Client has paid subscription for both. Then I evaluated Datadog Java Agent linked with Datadog Agent assuming Datadog commercial support will cover it. It works good for standard JVM metrics and standard traces but adding tags for traces and generating custom metrics requires application code to depend on some API. OpenTracing API is not bad but OpenTelemetry looks as future so it good that Datadog Java Agent supports it directly. However custom metrics in Datadog is quite raw with statsd client and I don't want to use it. It would be cool if Datadog Java Agent supports OpenTelemetry for metrics so I would have good API to send custom metrics. Otherwise I am close to use use Spring Micrometer with Datadog Registry sending custom metrics directly. Other advantage of using Datadog Java Agent vs OTEL Java Agent is continuous profiling.

**Comment by PerfectSlayer** [comment]
@kodstark You are right, only OpenTelemetry Tracing API is supported by the Datadog Java Agent for now. It does not mean the other signals won't be supported, only we started with tracing.
As you noticed, the documentation was not updated yet but was written and will be pushed soon ™️ , when all other language tracers are ready.
