### ISSUE TITLE
Enable client side rate sampling (percentage based)

### ISSUE THREAD

**Issue by akhil-karanth** [DataDog/dd-trace-java#497]
I am looking to enable client side rate sampling (sample only a percentage of transactions) in my java service, by following your [documentation](https://docs.datadoghq.com/tracing/getting_further/trace_sampling_and_storage/#client-rate-sampling)
I am looking at this [file](https://github.com/DataDog/dd-trace-java/blob/8dd87a8d30695de5564c4e8fcd24eb6e14e7e056/dd-trace-ot/src/main/java/datadog/trace/common/DDTraceConfig.java) but dont any option.
How do i set this?

**Comment by tylerbenson** [comment]
Yeah, this is not currently an option in the Java client.  We had it very early on, but removed it in the beta.  We considered adding it back, but you're the first to ask for it.  Could you elaborate why you want the sampling in the client rather than leave it to the agent?

**Comment by akhilk14** [comment]
@tylerbenson
If i understand correctly, in agent based sampling, the client sends all the traces to the agent and the agent drops some of them. 
We are looking to downsample at the client rather than at the agent level, so that we only send a percentage of the traces/drop at the client as it leads to lower load on the client/lower CPU/less overhead on the application.

**Comment by tylerbenson** [comment]
@akhilk14 that's understandable. Are you seeing excessive CPU overhead when tracing?  Is that on the agent or client side (or both)?  How many traces per second is a single JVM generating in your application?

**Comment by randomanderson** [comment]
This was released.  You can now set sampling percentages in the client.  See #1102
