### ISSUE TITLE
Traces with 4XX http status codes marked as error in 1.6.0

### ISSUE THREAD

**Issue by nicolaspasqualispeya** [DataDog/dd-trace-java#5454]
We are noticing that traces with http status 4xx are being marked with errors by default since we updated to the latest agent `1.16.0`.

I think this behaviour was removed after the `1.13.0` release. (probably releated to [PR 5128](https://github.com/DataDog/dd-trace-java/pull/5128))

Couldnt find anything relevant in the changelog. Any ideas if this is a new default behaviour or bug in 1.16.0?

**Comment by amarziali** [comment]
👋  thanks for having opened an issue. The 1.13.0 accidentally introduced regressions on the server errors and we did some bugfix on 1.16.0

Would you mind providing more details about? Stacktraces if any, framework used (e.g. application server, libraries,...), http return codes, screenshot of span flamegraph would be helpful.

Thanks in advance

Andrea

**Comment by nicolaspasqualispeya** [comment]
sure! (also provided more info in a [help.datadoghq.com](https://help.datadoghq.com/) request with links). netty server, kotlin w/ktor and the java agent.

found an example case with a simple flamegraph of 401 responses being marked as error in `1.16.0` (probably due to a failure/exception reported downstream), but not in `1.15.3`.

flamegraph in 1.15.3 marked `Ok`
![1-15-3](https://github.com/DataDog/dd-trace-java/assets/99270514/38231ca7-2252-400a-a8fd-832e087237e7)

and in 1.16.0 marked `Error`
![1-16-0](https://github.com/DataDog/dd-trace-java/assets/99270514/ae309295-663e-46ba-b46d-8bc8137898b3)

**Comment by amarziali** [comment]
@nicolaspasqualispeya thanks for the details. I had a look and try to reproduce a similar use case with a simple netty pipeline but I've different results that are the expected ones:

![image](https://github.com/DataDog/dd-trace-java/assets/7393723/4d86ce29-3e52-4497-b817-27ca0c58b763)

I've a question: are you flagging manually the error (i.e.  `span.setTag(Tags.ERROR, true);`)? 

In this case this is expected because, as soon as the span is manually flagged as errored, this takes priority regardless the http status code of the response. If it's the case and you still want to have the http response decide about flagging or not the span as error, I may suggest you do not add the error tag at all. You can still add the other tags like error type, message and stacktrace.

If the answer is not fitting what it's really happened, could you please try to provide a small reproducer app? You can use the ticket you already opened and the customer service will escalate directly to engineering for further analysis. 

Thanks in advance for your answer

Andrea

**Comment by amarziali** [comment]
Closing as inactive. If other investigation or clarification needed please feel free to reopen.

**Comment by dgswan** [comment]
For others, who faced similar issues, please see https://github.com/DataDog/dd-trace-java/issues/7288#issuecomment-2214098274.
