### ISSUE TITLE
Support for JMS @MessageDriven Beans

### ISSUE THREAD

**Issue by Gavagai-Marc** [DataDog/dd-trace-java#5544]
Hi, good afternoon!

We have been using the Java Agent for a few weeks and have been unable to get any JMS consumer traces (but the Producer traces are working). This leaves some of our most business-relevant traces out of scope and isn't good for us.

After checking the instrumentation code for JMS, we realized the current code only auto-instruments `MessageListener` when the `MessageConsumer` is managed manually. Maybe auto-instrumentation should be done also on classes implementing MessageListener? 

Also, we're guessing a feature like this could take some time to get implemented and released. Do you think there's any way to quick-fix this for now until the agent supports our use-case?

Many thanks!

**Comment by mcculls** [comment]
Hi @Gavagai-Marc - the issue with auto-instrumenting anything that implements `MessageListener` is that there are some tracing details that we can only support when we have access to the session where the listener was registered. We would also have to be careful when listeners are nested, otherwise you would end up with duplicate spans.

When you say you've been unable to get consumer traces, what client are you using to consume the JMS messages - is it using JMS 1 (javax.jms) or JMS 2 (jakarta.jms) ?  Also is is direct JMS or is it sending the message over something like SQS with a JMS adapter on each side?

If you haven't done so already I would recommend contacting support with details about the libraries you're using and [tracer debug logs](https://docs.datadoghq.com/tracing/troubleshooting/tracer_debug_logs/?code-lang=java) for both the producing and consuming JVMs.

**Comment by bm1549** [comment]
@Gavagai-Marc I'm happy to inform you that we support tracing `jakarta.jms` as of v1.21.0 with https://github.com/DataDog/dd-trace-java/pull/5868 🚀
