### ISSUE TITLE
[Question] How to add dd.trace_id to response for client call?

### ISSUE THREAD

**Issue by jmayday** [DataDog/dd-trace-java#5941]
I'm developing an application using Vert.x, DataDog is configured and works fine. Now I want to including trace_id in HTTP response for client calls (to make troubleshooting easier). I would like to have it in response headers or maybe response body. Anyway, I don't know how to do this. Could this be achieved automatically with DD agent configuration or I have to add code like below (how to access trace_id then)?

```
router
    .route()
    .handler(ctx -> {
        ctx.addHeadersEndHandler(handler -> {
            ctx.response().putHeader("trace_id", "<getting trace_id here>"); //?
        });
        ctx.next();
    });
```

**Comment by jmayday** [comment]
Thanks @PerfectSlayer !

**Comment by jmayday** [comment]
`CorrelationIdentifier.getTraceId()` gives me something like 1842684009828473616 for my `/rest/some-endpoint`.
I can't find any trace with such value later on.
And if I check APM -> Traces view and look for `/rest/some-endpoint` then trace_id has different value (and pattern): 6584147d00000000199287580f1e5b10

Why is that?

**Comment by PerfectSlayer** [comment]
Hey @jmayday 

The tracer starts producing traces using a new format: 128-bit trace identifier. It's a 32 hexadecimal char string where the previous one was a 64-bit integer. Here: `1842684009828473616` is a 64-bit trace identifier where `6584147d00000000199287580f1e5b10` is a 128-bit trace identifier.

From here, if you want to have `CorrelationIdentifier.getTraceId()` returning a 128-bit trace identifier, you have to enable the new format for logging by setting `DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED=true`.Check[ the related documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/#:~:text=dd.trace.128.bit.traceid.logging.enabled).

This was not the default behavior because it changes log output and might break some customers log parsing tools or configurations.

>[!NOTE]
> If you need to convert a 128-bit to 64-bit trace identifier, take the last half (16-char) hex value, and convert it base 10.  
> You can also use this playground with your trace identifier: [from 128-bit to 64-bit TID](https://go.dev/play/p/Obs-p-h4dwn) and [from 64-bit to partial 128-bit TID](https://go.dev/play/p/JSl52aLexJq)

**Comment by jmayday** [comment]
@PerfectSlayer thanks!
