### ISSUE TITLE
Unclear origin of vulnerable dependency (jackson-databind)

### ISSUE THREAD

**Issue by jmayday** [DataDog/dd-trace-java#5972]
I need some help regarding APM. On APM view, there is a "Security" tab, which shows Vulnerable Libraries. It claims there are some vulnerabilities in my project, coming from libraries in particular versions. I don't know where Datadog is getting that info from. Versions do not match with what I use in my project. For example: DD claims I'm using some old version of _jackson-databind_ library while _mvn dependency:tree_ doesn't confirm it. Could someone explain me how it works?

![image](https://github.com/DataDog/dd-trace-java/assets/10167533/d5dc4f30-62d3-4265-b0bd-3c4947f69df6)

PS. I tried to get some help Datadog Slack, but no one responded to my post.

**Comment by manuel-alvarez-alvarez** [comment]
Hello @jmayday,

First of all, apologies for the absence of a response in the Slack message.

From the _Security tab_ you will get a full inventory of the dependencies present in your application, even those that are hidden from a Maven standpoint (e.g. shaded dependencies that are embedded and won't show up in Maven's dependency tree command). 

In order to assist you further, you can create a support ticket with the organization and service where the vulnerable library is present or share with us the output of the `mvn dependency:tree` command.

**Comment by jmayday** [comment]
Done. Request #1374420

**Comment by manuel-alvarez-alvarez** [comment]
Hello @jmayday, ticket received and we are going over the dependencies, we will come back to you as soon as we trace the source of the dependency.

**Comment by manuel-alvarez-alvarez** [comment]
Dear @jmayday, 

We've finally tracked the source of the dependency, `net.sf.ehcache:ehcache:2.10.6` shades `com.fasterxml.jackson.core:jackson-databind:2.9.6` (it's available at _rest-management-private-classpath/META-INF/maven/com.fasterxml.jackson.core/jackson-databind/pom.properties_). 

In order to proceed, our recommendations are:

- Update to the latest ehcache 3.x (e.g. `org.ehcache:ehcache:3.10.8`) which is the commended solution
- Update to the latest ehcache 2.x (e.g. `net.sf.ehcache:ehcache:2.10.9.2`), it still shades `com.fasterxml.jackson.core:jackson-databind:2.11.1` but has less CVEs associated.

On our side, we are working on improving the information shown in cases like this, so it will be easier for you to clearly identify where vulnerable dependencies are coming from.

**Comment by jmayday** [comment]
Thanks @manuel-alvarez-alvarez!
