### ISSUE TITLE
Java 21 Support for trace agent.

### ISSUE THREAD

**Issue by sinsuren** [DataDog/dd-trace-java#5999]
Hi Team,
Any update by when DD agent will support java 21 sdk.

**Comment by am312** [comment]
Java 21 will work but is considered beta.  Compatibility [documentation](https://github.com/DataDog/documentation/blob/master/content/en/tracing/trace_collection/compatibility/java.md) will be updated shortly.  Thanks

**Comment by sinsuren** [comment]
<img width="1463" alt="Screenshot 2023-10-06 at 9 39 54 PM" src="https://github.com/DataDog/dd-trace-java/assets/6632645/29447ac9-f281-46cd-81ef-ff2367988180">
As of now metrics stops showing with jdk 21.

**Comment by mcculls** [comment]
I'm getting metrics running a simple spring-based application with Java 21 - is the JVM the only thing that changed? Could you also give the the full Java version?

**Comment by sinsuren** [comment]
```

FROM openjdk:21-slim-buster

RUN apt-get update \
    && apt-get install -yqq curl \
    && mkdir -p /root/env 

COPY --from=artifactory /dd-java-agent.jar /root/env/dd-java-agent.jar
COPY --from=artifactory /usr/local/bin/grpcurl /usr/local/bin/grpcurl

ENTRYPOINT ["/root/env/entrypoint.sh"]

**Comment by sinsuren** [comment]
<img width="1255" alt="Screenshot 2023-10-07 at 12 03 59 AM" src="https://github.com/DataDog/dd-trace-java/assets/6632645/d8bfcbc5-e2ad-46bb-a603-4f48d0708f8e">

This is only change which I did to make things work again.

**Comment by sinsuren** [comment]
![changes](https://github.com/DataDog/dd-trace-java/assets/6632645/57dadada-1b61-488c-ad2e-c8742df16ffc)
This is only change which I did to make things work again.

**Comment by sinsuren** [comment]
![Untitled design](https://github.com/DataDog/dd-trace-java/assets/6632645/3261a9d3-dae7-4caf-bdba-2f558484c3d4)

This is only change which I did to get dd metrics to get published.

**Comment by mcculls** [comment]
Which version of the Java tracer are you using?

It could be related to changing `sourceCompatibility`, which is also used as the default `targetCompatibility`. Setting this to `21` will generate bytecode at that higher level. If you're using an older version of the Java tracer (ie. before `1.12.x`) then it could end up skipping that bytecode because it uses an older version of byte-buddy which was released before Java 21.

If that's the case then upgrading to the latest Java tracer (or at least `1.12.1`) should help.

Another way to confirm this would be to change everything to `21` but leave `sourceCompatibility` set to `17`

**Comment by sinsuren** [comment]
Latest agent worked fine with java 21.

@mcculls @am312 thanks for your time.
