### ISSUE TITLE
Spring security - hideUserNotFoundExceptions should not be change to false

### ISSUE THREAD

**Issue by cdeverre** [DataDog/dd-trace-java#6072]
We are using the datadog agent for our spring application, and recently we saw that you forced a spring security boolean to false.

Initial commit that add this behaviour : https://github.com/DataDog/dd-trace-java/commit/a4a33e4a27b721e11047e68d20df6582d53219d7

And a commit to only activate this behaviour with ActiveSubsystems.APPSEC_ACTIVE : 
https://github.com/DataDog/dd-trace-java/pull/5756/files

This modification change the standard behaviour of the method : `org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate` 
and make it impossible for us to customize if we want this boolean to be set to true or false.

Furthermore, here is the documentation for this boolean:

> By default the AbstractUserDetailsAuthenticationProvider throws a BadCredentialsException if a username is not found or the password is incorrect. Setting this property to false will cause UsernameNotFoundExceptions to be thrown instead for the former. Note this is considered less secure than throwing BadCredentialsException for both exceptions.

I don't think the datadog agent should force a behaviour that change a security aspect of an application.

**Comment by ValentinZakharov** [comment]
Hello @cdeverre, thanks a lot for the report. 
Indeed there's a bug - expected behaviour should not breaking the app.
While we are working on fix, you can disable the spring security instrumentation with one of the following options:
- set System Property: `-Ddd.integration.spring-security.enabled=false`
- set Environment Variable: `DD_INTEGRATION_SPRING_SECURITY_ENABLED=false`

The AppSec will keep working, without User Events Tracking feature.
