### ISSUE TITLE
Unified Service Tagging sometimes missing

### ISSUE THREAD

**Issue by creatorKoo** [DataDog/dd-trace-java#6839]
By default, Unified Service Tagging is automatically injected by a java agent. My current environment is an aws eks environment, using kubernetes

In most cases, it is injected like below
<img width="362" alt="image" src="https://github.com/DataDog/dd-trace-java/assets/7449353/23e50aa7-757b-47c8-a92d-eecfb0751fe2">.

But for some pods, the injection fails and there is no env value, so it looks like below
<img width="321" alt="image" src="https://github.com/DataDog/dd-trace-java/assets/7449353/d4905aac-586f-4cf1-9d7f-25e30e4a4644">

So I can't trust this feature and the env value inside the pod.
As a workaround, I decided to use DD_SERVICE as fixed value. (modify deployment.yaml)

Please fix this feature so I can trust it

**Comment by amarziali** [comment]
👋 Hello thanks for having opened an issue. Unfortunately this is not linked to the java tracer but to universal service monitoring.
The best process to follow would be to file a case directly on datadog support (https://www.datadoghq.com/support/). 
I'm hence closing this issue here since it's not actionable on this project.
Thanks
