### ISSUE TITLE
Question: Ask for help about IDEA load the project failed

### ISSUE THREAD

**Issue by steverao** [DataDog/dd-trace-java#7347]
I prepared my project environment according to [relevant document](https://github.com/DataDog/dd-trace-java/blob/master/BUILDING.md). I can build the project by following command and get final Agent:
```
./gradlew clean assemble
```
But I can't load the project correctly by IDEA, It seems everything is ready according to [relevant document](https://github.com/DataDog/dd-trace-java/blob/master/BUILDING.md). 
![image](https://github.com/user-attachments/assets/1dcb66a2-1da8-4cae-9aa4-8578e1d34d58)

When I load the project by gradle, it will print following error logs:
```shell
Caused by: org.gradle.jvm.toolchain.internal.NoToolchainAvailableException: No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific} for LINUX on x86_64.
Caused by: org.gradle.jvm.toolchain.internal.ToolchainDownloadFailedException: No locally installed toolchains match and toolchain auto-provisioning is not enabled.
```
Is there anyone came across the problem before? Hope you can give me some hint, I extremely appreciate for your help in advance!❤️

**Comment by nayeem-kamal** [comment]
Hi @steverao. I believe you may need to install java 11 on your system and set an env variable to point to the install directory so that our tracer can access it during build time. A snippet from our build guide:

> The JDK versions 8, 11, 17 and 21 must be installed
The JAVA_8_HOME, JAVA_11_HOME, JAVA_17_HOME, JAVA_21_HOME and JAVA_GRAALVM17_HOME must point to their respective JDK location,
The JDK-8 bin directory must be the only JDK on the PATH (e.g. $JAVA_8_HOME/bin).
The JAVA_HOME environment variable may be unset. If set, it must point to the JDK 8 location (same as JAVA_8_HOME),
>
The build guide is available [here](https://github.com/DataDog/dd-trace-java/blob/master/BUILDING.md). Please reach out again if this doesn't work for you.

**Comment by nayeem-kamal** [comment]
Hi @steverao. Could you share your intellij jdk setup as well? This isn't a common issue that we are familiar with but we can try to help you debug

**Comment by steverao** [comment]
> Hi @steverao. Could you share your intellij jdk setup as well? This isn't a common issue that we are familiar with but we can try to help you debug

Sure, in fact, I cloned the project in a linux server(due to network reason) and connect it by the Jetbrains Client(2023.1).
![image](https://github.com/user-attachments/assets/d611b787-8bec-4d1c-a566-c085259b209d)
![image](https://github.com/user-attachments/assets/b6920410-ea9f-4b3e-a5c9-5801cca16d40)

**Comment by nayeem-kamal** [comment]
Thanks @steverao. Can you try manually registering all of the jdk's in intellij? 
the `No locally installed toolchains match and toolchain auto-provisioning is not enabled` message suggests that Intellij wasn't able to find the JDKs installed on the machine and has not been configured to download them on-demand

My suspicion is that manually registering them should therefore fix it. Let me know if you have further issues.

**Comment by steverao** [comment]
I removed the `.idea/` in project and reload the project again, it works for me now. Thank you very much!
