### ISSUE TITLE
How to build dd-java-agent with logging enabled?

### ISSUE THREAD

**Issue by JJonesAtAvaya** [DataDog/dd-trace-java#739]
I am trying to build a debug build of the java trace agent with some logging added, however, it seems to be explicitly excluding org.slf4j from being utilized, esp in the file

    src/main/java/datadog/trace/agent/TracingAgent.java

Please advise, thank you

**Comment by tylerbenson** [comment]
We use Slf4j's [SimpleLogger](https://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html) inside the agent.  You can control the log output by using the system properties documented on that class.  The only difference is we remap the package name, so instead of
`-Dorg.slf4j.simpleLogger.defaultLogLevel=debug` you must use `-Ddatadog.slf4j.simpleLogger.defaultLogLevel=debug`

If you have the code checked out and wish to build a modified agent, run the following command:
`./gradlew :dd-java-agent:shadowJar`

This will result in an agent jar in the following path:
`dd-java-agent/build/libs/`

Does that help?

**Comment by JJonesAtAvaya** [comment]
Thank you, trying: 

    ./gradlew :dd-java-agent:shadowJar

I still get

    /Users/julia15/datadog/agent.0.24.0/dd-trace-java/dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java:19: error: package org.slf4j does not exist

When adding this to the file TracingAgent.java:

    import lombok.extern.slf4j.Slf4j;

    /** Entry point for initializing the agent. */
    @Slf4j
    public class TracingAgent {

**Comment by tylerbenson** [comment]
Ah, I see... yeah, TracingAgent is not a safe point to use Slf4j.  You'll notice, elsewhere in that class we just use `System.out`. May I ask what are you trying to accomplish?

**Comment by JJonesAtAvaya** [comment]
Trying to figure out why I'm unable to send traces from my java app inside a Docker container.

System.out will be fine, I'll try that, thank you

**Comment by tylerbenson** [comment]
Ok.  I suggest enabling debug logging.  If that doesn't highlight anything specific, please contact our amazing support team and they should be able to help.  Thanks for reaching out!

**Comment by JJonesAtAvaya** [comment]
It worked!  Thanks very much
