### ISSUE TITLE
Kafka client  Instrument don't have peer hostname

### ISSUE THREAD

**Issue by peachisai** [DataDog/dd-trace-java#7396]
Hi
I am trying analyse the traces from DD java agent. I found kafka client instrument using `messaging.kafka.bootstrap.servers` to 
record the peer address, but other MQ or components ,such as Rabbitmq , grpc using `peer.hostname`, or http has `http.hostname` tag.
I thought It is strange that kafka client instrument has a unique tag to record the peer address.
Is there any special reason kafka client instrument using a special tag to record the peer address?
If possible the kafka client instrument  could add a new common tag `peer hostname`?
I would like to contribute to this.

**Comment by vandonr** [comment]
`messaging.kafka.bootstrap.servers` is not exactly the same as `peer.hostname`, because it's not the address of the peer which is going to receive the message, but the address of the whole cluster.
The peer or broker to which the message is actually being sent is "decided" later, in a different thread, so we don't have access to this information when we create the "produce" span, which is why we don't record it.

**Comment by peachisai** [comment]
> `messaging.kafka.bootstrap.servers` is not exactly the same as `peer.hostname`, because it's not the address of the peer which is going to receive the message, but the address of the whole cluster. The peer or broker to which the message is actually being sent is "decided" later, in a different thread, so we don't have access to this information when we create the "produce" span, which is why we don't record it.

Thank you for the reply, I got it
