### ISSUE TITLE
Missing ExecutionSample and ObjectAllocationSample events in Java 21

### ISSUE THREAD

**Issue by sivachandran** [DataDog/dd-trace-java#7590]
Hi,

I profiled a simple Java application with dd-trace-dd 1.39.0 using OpenJDK 21. The resultant JFR has less no. of `jdk.ExecutionSample` and no `jdk.ObjectAllocationSample`. When I tried to convert the JFR into pprof using async-profiler's `converter.jar` the resultant profile is empty which confirms the missing events. `jfr` cli tool also confirms there are no `jdk.ObjectAllocationSample` and just 76 `jdk.ExecutionSample` events for 2mins profile.

The problem is only with OpenJDK 21. The same setup with OpenJDK 17 works fine and produces JFR with both of these events.

Attached the JFR for your reference.
[jfr-profile-openjdk-21-missing-events.jfr.gz](https://github.com/user-attachments/files/16941899/jfr-profile-openjdk-21-missing-events.jfr.gz)

**Comment by jbachorik** [comment]
Hi @sivachandran - you are right, those events may be missing since we may be using datadog specific events to record CPU, wallclock and allocation profiles, depending on the Java version, architecture etc.

Also, I want to point out that Datadog profiler is not a generic Java profiler (see https://github.com/DataDog/java-profiler?tab=readme-ov-file#disclaimer) and if you want to profile your Java application but not use Datadog UI you should rather use `async-profiler` (which you seem to be using already, considering that you tried the converter tool) which is a full-fledged command line Java profiler.

**Comment by jbachorik** [comment]
No, we are not planning to drop JFR (however, on certain systems, eg. J9, it is not available).
Also, there is no problem with such usage, but honestly, I would go for async-profiler if you are not using DD infrastructure anyway. There is no upside to using DD profiler instead of async-profiler as a general CLI profiling tool.

**Comment by sivachandran** [comment]
I want to stick with DD profiler as its ability to send the profiles to the configured agent nicely fits with my existing architecture. I believe I need to write a wrapper for async-profiler to achieve the same.

**Comment by jbachorik** [comment]
Yes, I see. As I said, there is no problem with such usage.
An alternative to disabling the dd profiler is to make your pipeline aware of `datadog.ExecutionSample` (CPU profiler), `datadog.MethodSample` (Wallclock profiler) and `datadog.ObjectSample` (allocation profiler) events.
