### ISSUE TITLE
DDTracer.inject fails on datadog.opentracing.propagation.ExtractedContext

### ISSUE THREAD

**Issue by dehun** [DataDog/dd-trace-java#834]
Steps to reproduce
1. create span
2. inject it into carrier with `datadog.opentracing.DDTracer#inject`
3. extract it from carrier with `datadog.opentracing.DDTracer#extract`
4. inject just extracted `SpanContext` into another carrier with `datadog.opentracing.DDTracer#inject`

```
java.lang.ClassCastException: datadog.opentracing.propagation.ExtractedContext cannot be cast to datadog.opentracing.DDSpanContext
                     	at datadog.opentracing.DDTracer.inject(DDTracer.java:332)
```

**Comment by tylerbenson** [comment]
Could you explain a bit what you're trying to do?  Why not inject the original span's context?

**Comment by dehun** [comment]
We have scala codebase and we used datadog agent with automatic instrumentation(`-javaagent:$(pwd)/dd-java-agent.jar`). We encountered issues with it, and decided to do manual instrumentation instead using scala implicits. So we built a thin wrapper on top of opentracing api.
We do use grpc, and we want to serialize `SpanContext` over the network.  
I wrote a simple test that ensures that we can do forwarding of this `SpanContext`. 
Given microservices `A`, `B`, `C` I want to send `SpanContext` from `A` to `B` and then from `B` to `C`. 
We encounter issue on sending from `B` to `C` because we don't have original `DDSpanContext` anymore, but only `ExtractedContext`.

Both `DDSpanContext` and `ExtractedContext` are extending `SpanContext`. Expectation was that `DDTracer` would be able to serialize `ExtractedContext`.
For serialization we use `TextMap`, and we serialize like 
```
  private val wireFormat = io.opentracing.propagation.Format.Builtin.TEXT_MAP
  private[tracing] def toWire(sc: SpanContext): Option[WireRep] = {
    ...
    tracer.inject(sc, wireFormat, wireRep.carrier)
   ...
  }
```

**Comment by randomanderson** [comment]
This is an old ticket but I recently dealt with another person trying to do something similar so I thought I'd share.

There are two options:

**Option 1**: Forwarding the textmap/carrier
If "B" is just a dumb proxy, and since you're already using your own serialization, there is no need to create the ExtractedContext in B.  You can just forward the exact same map to the next service

**Option 2**: Creating a span in service B
If B is a service in your distributed trace, you should be creating a span in B with extracted context from the created span.  eg:

```
Span spanB = tracer.buildSpan("httpServerSpan").asChildOf(extractedContext).start()
...
tracer.inject(spanB.context(), ...);
```

Most likely, Service B is the true parent of Service C in which case you want to create a span to show that (Option 2)

**Comment by randomanderson** [comment]
Closing for now.  If more assistance is needed, comment on this thread and I'll reopen
