### ISSUE TITLE
Every new run creates dozens of .jar in /tmp

### ISSUE THREAD

**Issue by knokio** [DataDog/dd-trace-java#938]
We have been dealing with something really strange for a few months: thousands of "jarXXXX.jar" in /tmp in the machines running JVM with dd-trace-java.

I investigated and concluded that each JVM run (cronjobs running java commands) generate ~40 of these jar files.

What are they? Why aren't they cleaned up? Attached are some screenshots.

<img width="306" alt="Screenshot 2019-08-06 at 11 42 00" src="https://user-images.githubusercontent.com/667278/62533711-44e7c080-b83f-11e9-852e-63a271887cfc.png">
<img width="588" alt="Screenshot 2019-08-06 at 11 42 13" src="https://user-images.githubusercontent.com/667278/62533712-44e7c080-b83f-11e9-9622-92a038dece5f.png">

**Comment by randomanderson** [comment]
This is a known issue with Byte Buddy.  Classes need to be in a jar in order to be injected into the bootstrap classloader.  Byte Buddy was not deleting those jars after use.

We resolved this issue with ByteBuddy a few days ago (https://github.com/raphw/byte-buddy/pull/698 and https://github.com/raphw/byte-buddy/commit/89f85680748ee307044ee7558cd5a4a845592ddc) . It will be fixed here once we update to the latest Byte Buddy version.

**Comment by knokio** [comment]
Thanks for the quick reply @randomanderson. I'll wait for the next release

**Comment by tylerbenson** [comment]
Should be fixed in #940

**Comment by knokio** [comment]
It's ok @tylerbenson we'll wait. Should I close the ticket?

**Comment by tylerbenson** [comment]
We will close it when it gets released.  Thanks for the report.

**Comment by changjiang2016** [comment]
If you do not want creates dozens of .jar in /tmp,you can try to  specify the parent directory of the tmp directory using the java method like this.
public static File createTempFile(String prefix, String suffix,File directory).I don't know if the community doesn't support this, it's just a suggestion.

**Comment by randomanderson** [comment]
This has been resolved in the 0.32.0 release
