### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by changjiang2016** [DataDog/dd-trace-java#943]
When I gradlew build from the root project,the error  about the jmh occured,event though I run the gradle command ./gradlew --continue build.
Execution failed for task ':dd-java-agent:benchmark:compileJmhJava'.
> Could not resolve all dependencies for configuration ':dd-java-agent:benchmark:jmh'.
   > A build operation failed.
         null
      > java.lang.StackOverflowError (no error message)

**Comment by tylerbenson** [comment]
Thanks for the report... We can certainly look into fixing this, but meanwhile we usually don't use the `build` task.  If you want to build the agent jar, try running this task: `:dd-java-agent:shadowJar`

**Comment by changjiang2016** [comment]
@tylerbenson,Thank you for your reply.The tips works.But a problem  occured when I import the project to IDEA.,The IDEA import dependency fails because of the dependency download timeout. So I can't use IDEA for code editing. It is nightmare for me.Have you encountered this situation? How do you import IDEA in actual production?Thank you

**Comment by tylerbenson** [comment]
there are certainly a LOT of dependencies that get downloaded.  It might help to prime the cache by running a `gradle test` first, since I believe it shares the same cache as the command line.  Another option would be to temporarily comment out a bunch of projects in `settings.gradle` and see if that helps.

**Comment by randomanderson** [comment]
#1792 fixes this
